### ISSUE TITLE
Some clients spin out of control and spawn many concurrent sessions

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#79] opened 2015-06-22 21:35 UTC
We're seeing instances where a single Android app user spawn hundreds of simultaneous connections, chewing through huge amounts of data. Occurrences appear random, but have happened several time and is troubling enough that it should be investigated.

The session ramp-up from a single IP will look like:

![screen_shot_2015-06-22_at_12 30 51_pm_1024](https://cloud.githubusercontent.com/assets/442483/8293601/749d46b2-18eb-11e5-936c-70af2d42cc74.png)

And that client will wind up with session_id counts and data consumption that looks like this:

![screen_shot_2015-06-22_at_12 26 59_pm_1024](https://cloud.githubusercontent.com/assets/442483/8293615/981151c4-18eb-11e5-81ea-af7a9e28c986.png) 

In two recent instances we've tracked, the UA has been identical:

KPCCAndroid-3.1.0-72 | Player/LG Player 1.0 for Android 4.4.2 (stagefright alternative)

It may even be the same device/user - we're not able to tell with the data we have.

Given how much data consumption is happening to a single user, and the fact that this is skewing our stream numbers, it seems worth putting in some cycles to either identify the issue or implement some additional instrumentation that would allow us to better track what's happening around these events.

**Comment by bricker** [comment] 2015-06-23 00:12
Hey Sean, are these requests/graphs for the KPCC API?

**Comment by sdillingham** [comment] 2015-06-23 00:14
They're actually graphs of requests to StreamMachine. Sorry - I should have
specified that upfront.

**Comment by bricker** [comment] 2015-06-23 00:17
Ooohhh I see. I know where I can start looking. Right now the app is pretty passive about killing old media players, relying on the audio focus rules to "release" them and GC to clean them out of the memory. There may be a bug in the audio focus rules, but either way I can make the app more aggressive about releasing old media players.

Actually, when adding the Live Rewind I'll pretty much be rewriting the Live Stream feature and how media players are handled, so this bug may resolve itself.

**Comment by ewr** [comment] 2015-06-23 17:13
Two more clients are going nuts this morning, both with that "Player/LG Player 1.0 for Android 4.4.2 (stagefright alternative)" UA. Together they've consumed 39GB in 2.5 hours and are still going.

I'm not sure what options we have to fix this, but I see this as a high-priority issue to fix without waiting for any new feature development.

**Comment by bricker** [comment] 2015-06-23 18:49
It's confusing to me that it's just that one UA. Can you possibly block that UA until I can get a fix in?

**Comment by ewr** [comment] 2015-06-23 21:46
Potentially. I'll have to discuss that option with @sdillingham.

Is there any event information currently being generated when the player creates new sessions? Even outside of these huge consumers, I'm seeing other cases where a surprising number of sessions are being generated by a single IP.

For instance, over a ~hour stretch this morning, a client showing as "KPCCAndroid-3.1.0-72 | Samsung SPH-L900 stagefright/1.2 (Linux;Android 4.4.2)" generated 242 session starts. Another (similar) IP with the same UA generated 182 sessions in that same period.

A client showing the UA of "KPCCAndroid-3.1.0-72 | Samsung SPH-L710 stagefright/1.2 (Linux;Android 4.4.2)" generated 154 sessions in 43 seconds overnight, generating new session requests roughly ~200ms apart at times.

**Comment by bricker** [comment] 2015-06-23 21:51
We're not sending anything to Mixpanel specifically when a new connection
is made, only when the user clicks the "Play" button. These multiple
connections are probably occurring when a user has a spotty connection and
the stream is going in and out. The old connections just aren't being
stopped or cleaned up correctly (maybe stuck in the "paused" state).

**Comment by ewr** [comment] 2015-06-23 21:55
But at 200ms between retries, clearly something in that logic is going really wrong. I do think for those last examples it is probably cleaning up the old players fine (since I don't see the same storm behavior), but something is causing it to spawn new connections way too often / quickly.

**Comment by bricker** [comment] 2015-06-23 22:17
I forget the exact logic but I think basically it starts a new player whenever internet connection becomes available (if it had previously been lost), so that callback may be getting hit more often than I thought it could be if the data connection is spotty, and maybe the audio focus rules are not taking effect. It needs to be debounced.

**Comment by bricker** [comment] 2015-07-10 09:52
My first attempt at fixing this is in 7496c2871e96c0676693e2339a32e228ddd72292 .

**Comment by sdillingham** [comment] 2015-07-20 22:29
@bricker this is just an FYI: This morning we saw a blip in stream delivery that caused at least one client to spawn a few hundred sessions. Here's the bandwidth blip we observed (times in this screenshot are ET):

![screen_shot_2015-07-20_at_12 56 18_pm_1024](https://cloud.githubusercontent.com/assets/442483/8788956/3d5e8184-2ef3-11e5-933e-48db7909b7c0.png)

And here is the UA for the runaway client showing their device and app version (it appears this happened on a client running the current production version 3.1.2):

![screen_shot_2015-07-20_at_1 17 55_pm_1024](https://cloud.githubusercontent.com/assets/442483/8788972/616a2b3c-2ef3-11e5-8753-1777f5d07f8d.png)

Given that you're rewriting the stream management code as part of the move to HLS, I'm inclined to focus our attention on putting together a robust pre-release plan for how we test HLS streaming. I need to confer with @vsinghkpcc our Product Manager, but one piece of that should be a large public beta test group that gets us coverage across a broader set of devices. I'll be following up out of band to discuss that more.

**Comment by bricker** [comment] 2015-07-20 22:35
Thanks. I agree, the HLS rewrite with almost certainly take care of this problem. It seems like it's a leak caused by not handling the lifecycle of the MediaPlayer objects correctly, but that class is being replaced by something lower-level and entirely different (ExoPlayer) and the lifecycle is managed more explicitly now and less players will be allocated in general. I have the HLS/live rewind mostly working now.

**Comment by bricker** [comment] 2015-08-10 09:06
I believe this will be fixed in v76, I won't close until it's confirmed.

**Comment by bricker** [comment] 2015-08-22 19:52
@sdillingham @ewr @vsinghkpcc Have you guys seen this problem come up since releasing v76 (the HLS release)?

**Comment by ewr** [comment] 2015-08-25 13:15
Looks like the last case that I noticed was August 4. I don't have the app version handy, though.

**Closed** 2016-03-23 20:20 UTC
