### ISSUE TITLE
Investigate unintended stream stops and restarts

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#66] opened 2015-05-06 23:57 UTC
This issue may need to be broken out into more discreet tasks, but the highest volume of bug reports have been around instances where the live stream starts playing on its own after audio has manually been stopped, or in some instances stops playing when the user backgrounds the app.

Desk issues for reference:

https://kpcc.desk.com/agent/case/12609
https://kpcc.desk.com/agent/case/12610
https://kpcc.desk.com/agent/case/12611
https://kpcc.desk.com/agent/case/12612
https://kpcc.desk.com/agent/case/12584
https://kpcc.desk.com/agent/case/12589
https://kpcc.desk.com/agent/case/12601
https://kpcc.desk.com/agent/case/12588
https://kpcc.desk.com/agent/case/12591

I haven't been able to reproduce this error on my Motorola Droid X, so the first step may be trying to identify the conditions under which this could occur.

**Comment by bricker** [comment] 2015-05-06 23:59
@sdillingham there was a problem reported where people upgraded the app and saw this problem, but it went away when the app was completely reinstalled. I think it has something to do with carryover from the old app.

**Comment by sdillingham** [comment] 2015-05-07 00:00
Interesting. Was there feedback from users somewhere indicating that reinstalling fixed the issue? I must have missed that.

**Comment by bricker** [comment] 2015-05-07 00:02
See this review on the Play Store from Jin-Kyung Yoo:

https://play.google.com/store/apps/details?id=com.skyblue.pra.kpcc&reviewId=Z3A6QU9xcFRPRldBWjVnd1VmRTBiaDNqZkw1aURYWEpkdTZLNy05TmtRZ1l2Z0Z1Z01vbmZISWpHbVV1enRFekdVMGxYRm40R084TkxmQTBPVFRmRWozQlBr

**Comment by sdillingham** [comment] 2015-05-07 00:04
Thanks for linking to that. Let me try reaching out to the users on Desk who reported the issue and see if reinstalling addresses the issue for them. If so, we can close this.

**Comment by bricker** [comment] 2015-05-07 00:07
Cool. Debugging this problem locally would be, er, "challenging" (trying not to use the word "impossible") since I can't really "upgrade" to a debug APK.

**Comment by bricker** [comment] 2015-05-07 00:08
Of course, if we can reproduce on a freshly-installed app, that's a whole different story.

**Comment by bricker** [comment] 2015-05-10 18:32
So I'm pretty sure I was able to reproduce this on a phone that didn't have the old app installed. It's an audio focus problem, I don't know why it's not happening on all phones but I'll run through the logic again.

**Comment by bricker** [comment] 2015-05-24 00:19
This is consistently reproducible on Lollipop. My device was previously on KitKat but I just got the OTA update from Verizon.

**Comment by bricker** [comment] 2015-05-24 00:25
This is fixed now. It was an obvious bug once I could reproduce. I don't know why it only happens on Lollipop.

**Closed** 2015-05-24 00:27 UTC
